"""empty message

Revision ID: 1c51ed4daa98
Revises: None
Create Date: 2015-08-17 11:06:24.244000

"""

# revision identifiers, used by Alembic.
revision = '1c51ed4daa98'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), server_default='0', nullable=True),
    sa.Column('record', sa.Integer(), server_default=sa.text(u'100'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
