"""text(false)

Revision ID: 252292496079
Revises: 527f071201da
Create Date: 2015-08-17 16:08:25.203000

"""

# revision identifiers, used by Alembic.
revision = '252292496079'
down_revision = '527f071201da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
