"""init db

Revision ID: 2bdb58fe665f
Revises: None
Create Date: 2015-08-17 11:28:34.168000

"""

# revision identifiers, used by Alembic.
revision = '2bdb58fe665f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), server_default='0', nullable=True),
    sa.Column('record', mysql.INTEGER(display_width=20), server_default=sa.text(u'100'), nullable=False),
    sa.Column('gender', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
