"""add gender again

Revision ID: 527f071201da
Revises: 43b278475089
Create Date: 2015-08-17 16:04:12.998000

"""

# revision identifiers, used by Alembic.
revision = '527f071201da'
down_revision = '43b278475089'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    ### end Alembic commands ###
