"""change user.record width

Revision ID: 59053b3d77da
Revises: 7c12db8d511
Create Date: 2015-08-17 14:00:00.246000

"""

# revision identifiers, used by Alembic.
revision = '59053b3d77da'
down_revision = '7c12db8d511'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import INTEGER


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", type_=sa.String(60))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", type_=sa.String(80))
    ### end Alembic commands ###
