"""empty message

Revision ID: 5923a21aee18
Revises: 1c51ed4daa98
Create Date: 2015-08-17 11:10:58.263000

"""

# revision identifiers, used by Alembic.
revision = '5923a21aee18'
down_revision = '1c51ed4daa98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    ### end Alembic commands ###
