"""delete gender

Revision ID: 7c12db8d511
Revises: 2bdb58fe665f
Create Date: 2015-08-17 11:33:30.199000

"""

# revision identifiers, used by Alembic.
revision = '7c12db8d511'
down_revision = '2bdb58fe665f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=False))
    ### end Alembic commands ###
